CREATE OR ALTER PROCEDURE Flix.LoginUser
	@Username NVARCHAR(64)
AS

SELECT CASE WHEN EXISTS (
	SELECT *
	FROM Flix.[User] U
	WHERE U.Username = @Username
)
THEN CAST(1 AS BIT)
ELSE CAST(0 AS BIT) END AS Result
GO

