IF OBJECT_ID(N'Flix.Netflix') IS NULL
BEGIN
	CREATE TABLE Flix.Netflix 
	(
		RowId INT NOT NULL IDENTITY(1, 1) PRIMARY KEY,
		ShowId NVARCHAR(20) NOT NULL,
		[Type] NVARCHAR(10) NULL,
		Title NVARCHAR(128) NULL,
		Director NVARCHAR(1024) NULL,
		[Cast] NVARCHAR(1024) NULL,
		Country NVARCHAR(1024) NULL,
		DateAdded NVARCHAR(64) NULL,
		ReleaseYear NVARCHAR(64) NULL,
		Rating NVARCHAR(10) NULL,
		Duration NVARCHAR(64) NULL,
		ListedIn NVARCHAR(1024) NULL,
		[Description] NVARCHAR(1024) NULL
	);
END